### ISSUE TITLE
masterview的xib没有显示在界面上

### ISSUE THREAD

**Issue by buzai** [Alexiuce/ScaryBugsMac#1]
我按照你的简书文章来的但是没有显示出来是为什么呢

**Comment by Alexiuce** [comment]
can you show me more details about the  code?

**Comment by buzai** [comment]
@Alexiuce I have fixed by myself. in the recent xcode new project it use storyboard,so....

**Comment by Alexiuce** [comment]
OK,Storyboard used in Xcode new project, so NSWindow maybe changed to NSWindowController
